apiVersion: v1
kind: Secret
metadata:
  name: mastodon-secrets
  namespace: mastodon
type: Opaque
data:
  # Postgres
  DB_PASS: <DB_PASS_B64>
  # Secrets
  SECRET_KEY_BASE: <SECRET_KEY_BASE_B64>
  OTP_SECRET: <OTP_SECRET_B64>

  # Web push
  VAPID_PRIVATE_KEY: <VAPID_PRIVATE_KEY_B64>
  VAPID_PUBLIC_KEY: <VALID_PUBLIC_KEY_B64>

  # SMTP
  SMTP_LOGIN: <SMTP_LOGIN_B64>
  SMTP_PASSWORD: <SMTP_PASSWORD_B64>

  # S3/Minio
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID_B64>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
